site_name: Advanced Laravel
nav:
  - "Главная": index.md
  - "Установка": installation.md
  - "Функционал":
      - "Console": features/console.md
      - "Filesystem": features/filesystem.md
      - "Model": features/model.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - php